# Numpy 简介

Numpy (Numerical Python 的简称) 是高性能科学计算和数据分析的基础包，提供了矩阵运算的功能。Numpy 主要有以下功能：

- ndarray - 一个具有向量算术运算和复杂广播 (broadcasting) 的多维数组对象
- 提供对数组数据进行快速运算的标准数学函数
- 用于读写磁盘数据的工具
- 线性代数，傅里叶变换操作

【注】上面提到的 `广播 (broadcasting)` 可以这么理解: 当有两个不同维度的数组 (array) 运算的时候，将低维的数组复制成高维数组参与运算 (因为 Numpy 运算的时候需要数组维度相同)

# Numpy 基础

## 创建 ndarray 

在 Numpy 中，最核心的数据结构是 ndarray, ndarray 代表的是多维数组。我们可以通过以下方式来创建 ndarray 对象:

- 转换一个 Python 列表
- 使用工厂函数 (如 arange) 来返回一个填充向量

下面展示几种方法来生成同一个向量 [0, 1, 2, 3, 4]

In [2]:
import numpy as np

In [5]:
# 转换一个 Python 列表
vec1 = np.array([0., 1., 2., 3., 4.])

# 使用 arange(start_inclusive, stop_exclusive, step_size)
vec2 = np.arange(0, 5, 1, dtype=float)

# 使用 linspace(start_inclusive, stop_inclusive, number_of_elements)
vec3 = np.linspace(0, 4, 5)

In [6]:
vec1

array([0., 1., 2., 3., 4.])

In [7]:
vec2

array([0., 1., 2., 3., 4.])

In [8]:
vec3

array([0., 1., 2., 3., 4.])

再来看看生成二维数组

In [9]:
# 转换一个 Python 列表
mat1 = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

# 使用 reshape 方法
mat2 = np.arange(8).reshape(2, 4)  # 2 行 4 列

In [10]:
mat1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [11]:
mat2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

三维数组

In [12]:
# 2 层 3 行 4 列
data_3d = np.arange(24).reshape(2, 3, 4)

In [13]:
data_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# 参考资料

- [numpy ndarray 之内功心法 - 知乎](https://zhuanlan.zhihu.com/p/39287693)
- [利用Python进行数据分析 第二版 (2017) 中文翻译笔记](https://github.com/BrambleXu/pydata-notebook/tree/94ab37630b0151293148d127c34b1190c6ace403)