# pad 

我们可以在一个 tensor 周围填充值，类似图像中的 padding 操作

In [2]:
import tensorflow as tf

In [8]:
t = [[2, 3, 4], [5, 6, 7]]
paddings = [[1, 2], [1, 2]]

In [9]:
with tf.Session() as sess:
    print(sess.run(tf.pad(t, paddings, "CONSTANT")))

[[0 0 0 0 0 0]
 [0 2 3 4 0 0]
 [0 5 6 7 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


[tensorflow tf.pad解析 - zhang_bei_qing的博客 - CSDN博客](https://blog.csdn.net/zhang_bei_qing/article/details/75090203)